use_frameworks!

platform :ios, '8.0'

target 'cocoa_grinwallet_Example' do
  pod 'cocoa_grinwallet', :path => '../'
  pod 'ObjectMapper', '~> 3.4'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'Result', '~> 4.1'

  target 'cocoa_grinwallet_Tests' do
    inherit! :search_paths

    
  end
end
